title: "Phocean.net"
description: "Homepage of Phocean"
url: "https://phocean.net"
author:
  name: "Jean-Christophe Baptiste"
  email: "jc@phocean.net"
  url: "https://phocean.net"

baseurl: /

# Liste des catégories
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/
    # exemple -> /category/informatique/

defaults:
  - scope:
      path: "img"
    values:
      image: true
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
      # layout utilisé -> _layouts/category

plugins:
  - jekyll-sitemap
  - jekyll-fontello

# Custom variables
version: "1.0.0"

# Options
permalink: pretty
custom_header: true
custom_nav_footer: false
reverse: false

