title: "Phocean.net"
description: "Homepage of Phocean"
url: "https://phocean.net"
author:
  name: "Jean-Christophe Baptiste"
  email: "jc@phocean.net"
  url: "https://phocean.net"

baseurl: /

defaults:
  - scope:
      path: "img"
    values:
      image: true

plugins:
  - jekyll-sitemap
  - jekyll-fontello

# Custom variables
version: "1.0.0"

# Options
permalink: /:year/:month/:title.html
custom_header: true
custom_nav_footer: false
reverse: false

str_next_page: "Next"  
str_previous_page: "Previous"
pagination_nr: 1
paginate_path: /blog/page:num/
