title: "Phocean.net"
description: "Homepage of Phocean"
url: "https://phocean.net"
author:
  name: "Jean-Christophe Baptiste"
  email: "jc@phocean.net"
  url: "https://phocean.net"

baseurl: /

defaults:
  - scope:
      path: "img"
    values:
      image: true

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-fontello

# Custom variables
version: "1.0.0"

# Options
permalink: /:year/:month/:title.html
custom_header: true
custom_nav_footer: false
reverse: false

pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/blog/page:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

